[package]
edition = "2021"
name = "s3x"
version = "0.1.0"

[dependencies]
aws-config = "1.6.1"
aws-sdk-s3 = "1.82.0"
aws-smithy-types = "1.3.0"
tokio = { version = "1.44.2", features = ["full"] }

[dev-dependencies]
file_diff = "1.0.0"
